version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: travago-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travago
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
networks:
  my_network:
    driver: bridge
